### ISSUE TITLE
[wordpress] WordPress.addDatabase() TypeError: Cannot read property 'service' of undefined

### ISSUE THREAD

**Issue by neilkuan** [pahud/cdk-fargate-patterns#36]
### WordPress.addDatabase() TypeError: Cannot read property 'service' of undefined in line 209.
https://github.com/pahud/cdk-fargate-patterns/blob/227d63ca145b3a2c973fb8365ce8a726924f7698/src/wordpress.ts#L206-L210

When I run  `cdk synth --app='lib/integ.wordpress.js'`
```bash
/private/tmp/cdk-fargate-patterns/lib/wordpress.js:117
            allowFrom: this.svc.service[0],
                                ^

TypeError: Cannot read property 'service' of undefined
    at WordPress.addDatabase (/private/tmp/cdk-fargate-patterns/lib/wordpress.js:117:33)
    at new WordPress (/private/tmp/cdk-fargate-patterns/lib/wordpress.js:16:24)
    at Object.<anonymous> (/private/tmp/cdk-fargate-patterns/lib/integ.wordpress.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Subprocess exited with error 1
```

Because use this method `addDatabase()` without define `this.svc` yet in line 80 to line 89.
When that time `this.svc` still equal `[]`, before you new DualAlbFargateService() in line 167.
https://github.com/pahud/cdk-fargate-patterns/blob/227d63ca145b3a2c973fb8365ce8a726924f7698/src/wordpress.ts#L80-L89 
 
https://github.com/pahud/cdk-fargate-patterns/blob/227d63ca145b3a2c973fb8365ce8a726924f7698/src/wordpress.ts#L167-L181

I will fix that.

**Comment by neilkuan** [comment]
cc @pahud
